# FROM gcc:11

# WORKDIR /app
# COPY main.cpp .

# RUN g++ -std=c++17 main.cpp -o main

# CMD ["./main"] 


# Build stage
FROM alpine:3.18 AS builder
RUN apk add --no-cache g++ make

WORKDIR /app
COPY main.cpp .
RUN g++ -std=c++17 main.cpp -o main

# Runtime stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
CMD ["./main"]